//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyWebsiteByAEF.DBModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MyDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MyDBEntities”部分中的连接字符串初始化新 MyDBEntities 对象。
        /// </summary>
        public MyDBEntities() : base("name=MyDBEntities", "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MyDBEntities 对象。
        /// </summary>
        public MyDBEntities(string connectionString) : base(connectionString, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MyDBEntities 对象。
        /// </summary>
        public MyDBEntities(EntityConnection connection) : base(connection, "MyDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<questionandanswer> questionandanswer
        {
            get
            {
                if ((_questionandanswer == null))
                {
                    _questionandanswer = base.CreateObjectSet<questionandanswer>("questionandanswer");
                }
                return _questionandanswer;
            }
        }
        private ObjectSet<questionandanswer> _questionandanswer;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<buginfo> buginfo
        {
            get
            {
                if ((_buginfo == null))
                {
                    _buginfo = base.CreateObjectSet<buginfo>("buginfo");
                }
                return _buginfo;
            }
        }
        private ObjectSet<buginfo> _buginfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<chatinfo> chatinfo
        {
            get
            {
                if ((_chatinfo == null))
                {
                    _chatinfo = base.CreateObjectSet<chatinfo>("chatinfo");
                }
                return _chatinfo;
            }
        }
        private ObjectSet<chatinfo> _chatinfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<errorlog> errorlog
        {
            get
            {
                if ((_errorlog == null))
                {
                    _errorlog = base.CreateObjectSet<errorlog>("errorlog");
                }
                return _errorlog;
            }
        }
        private ObjectSet<errorlog> _errorlog;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 questionandanswer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToquestionandanswer(questionandanswer questionandanswer)
        {
            base.AddObject("questionandanswer", questionandanswer);
        }
    
        /// <summary>
        /// 用于向 buginfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobuginfo(buginfo buginfo)
        {
            base.AddObject("buginfo", buginfo);
        }
    
        /// <summary>
        /// 用于向 chatinfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTochatinfo(chatinfo chatinfo)
        {
            base.AddObject("chatinfo", chatinfo);
        }
    
        /// <summary>
        /// 用于向 errorlog EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToerrorlog(errorlog errorlog)
        {
            base.AddObject("errorlog", errorlog);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="solutionmanageModel", Name="buginfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class buginfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 buginfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="triggerBug">TriggerBug 属性的初始值。</param>
        public static buginfo Createbuginfo(global::System.String id, global::System.String triggerBug)
        {
            buginfo buginfo = new buginfo();
            buginfo.Id = id;
            buginfo.TriggerBug = triggerBug;
            return buginfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TriggerBug
        {
            get
            {
                return _TriggerBug;
            }
            set
            {
                OnTriggerBugChanging(value);
                ReportPropertyChanging("TriggerBug");
                _TriggerBug = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TriggerBug");
                OnTriggerBugChanged();
            }
        }
        private global::System.String _TriggerBug;
        partial void OnTriggerBugChanging(global::System.String value);
        partial void OnTriggerBugChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpectedBehavior
        {
            get
            {
                return _ExpectedBehavior;
            }
            set
            {
                OnExpectedBehaviorChanging(value);
                ReportPropertyChanging("ExpectedBehavior");
                _ExpectedBehavior = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpectedBehavior");
                OnExpectedBehaviorChanged();
            }
        }
        private global::System.String _ExpectedBehavior;
        partial void OnExpectedBehaviorChanging(global::System.String value);
        partial void OnExpectedBehaviorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ObservedBehavior
        {
            get
            {
                return _ObservedBehavior;
            }
            set
            {
                OnObservedBehaviorChanging(value);
                ReportPropertyChanging("ObservedBehavior");
                _ObservedBehavior = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ObservedBehavior");
                OnObservedBehaviorChanged();
            }
        }
        private global::System.String _ObservedBehavior;
        partial void OnObservedBehaviorChanging(global::System.String value);
        partial void OnObservedBehaviorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DoneWhat
        {
            get
            {
                return _DoneWhat;
            }
            set
            {
                OnDoneWhatChanging(value);
                ReportPropertyChanging("DoneWhat");
                _DoneWhat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DoneWhat");
                OnDoneWhatChanged();
            }
        }
        private global::System.String _DoneWhat;
        partial void OnDoneWhatChanging(global::System.String value);
        partial void OnDoneWhatChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Repaired
        {
            get
            {
                return _Repaired;
            }
            set
            {
                OnRepairedChanging(value);
                ReportPropertyChanging("Repaired");
                _Repaired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Repaired");
                OnRepairedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Repaired;
        partial void OnRepairedChanging(Nullable<global::System.Boolean> value);
        partial void OnRepairedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="solutionmanageModel", Name="chatinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class chatinfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 chatinfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="message">Message 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="readFlag">ReadFlag 属性的初始值。</param>
        public static chatinfo Createchatinfo(global::System.String id, global::System.String name, global::System.String message, global::System.DateTime createTime, global::System.Boolean readFlag)
        {
            chatinfo chatinfo = new chatinfo();
            chatinfo.Id = id;
            chatinfo.Name = name;
            chatinfo.Message = message;
            chatinfo.CreateTime = createTime;
            chatinfo.ReadFlag = readFlag;
            return chatinfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReadFlag
        {
            get
            {
                return _ReadFlag;
            }
            set
            {
                OnReadFlagChanging(value);
                ReportPropertyChanging("ReadFlag");
                _ReadFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadFlag");
                OnReadFlagChanged();
            }
        }
        private global::System.Boolean _ReadFlag;
        partial void OnReadFlagChanging(global::System.Boolean value);
        partial void OnReadFlagChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="solutionmanageModel", Name="errorlog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class errorlog : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 errorlog 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="errorMsg">ErrorMsg 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static errorlog Createerrorlog(global::System.String id, global::System.String errorMsg, global::System.DateTime createTime)
        {
            errorlog errorlog = new errorlog();
            errorlog.Id = id;
            errorlog.ErrorMsg = errorMsg;
            errorlog.CreateTime = createTime;
            return errorlog;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ErrorMsg
        {
            get
            {
                return _ErrorMsg;
            }
            set
            {
                OnErrorMsgChanging(value);
                ReportPropertyChanging("ErrorMsg");
                _ErrorMsg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ErrorMsg");
                OnErrorMsgChanged();
            }
        }
        private global::System.String _ErrorMsg;
        partial void OnErrorMsgChanging(global::System.String value);
        partial void OnErrorMsgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="solutionmanageModel", Name="questionandanswer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class questionandanswer : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 questionandanswer 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="question">Question 属性的初始值。</param>
        /// <param name="answer">Answer 属性的初始值。</param>
        /// <param name="hits">Hits 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static questionandanswer Createquestionandanswer(global::System.String id, global::System.String question, global::System.String answer, global::System.Int32 hits, global::System.DateTime createTime)
        {
            questionandanswer questionandanswer = new questionandanswer();
            questionandanswer.Id = id;
            questionandanswer.Question = question;
            questionandanswer.Answer = answer;
            questionandanswer.Hits = hits;
            questionandanswer.CreateTime = createTime;
            return questionandanswer;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            set
            {
                OnKeywordChanging(value);
                ReportPropertyChanging("Keyword");
                _Keyword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keyword");
                OnKeywordChanged();
            }
        }
        private global::System.String _Keyword;
        partial void OnKeywordChanging(global::System.String value);
        partial void OnKeywordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hits
        {
            get
            {
                return _Hits;
            }
            set
            {
                OnHitsChanging(value);
                ReportPropertyChanging("Hits");
                _Hits = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hits");
                OnHitsChanged();
            }
        }
        private global::System.Int32 _Hits;
        partial void OnHitsChanging(global::System.Int32 value);
        partial void OnHitsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();

        #endregion

    
    }

    #endregion

    
}
